enum class Status : uint8_t{
    // INFORMATIONAL
    SUCCESS,
    NOTHING_TO_READ,
    INCOMPLETE_MESSAGE,
    NOTHING_TO_DO,
    EXCEEDED_CLIENT_BUFFER_SIZE,

    // CLIENT ERRORS OR MALICIOUS USER
    INVALID_CLIENT,
    INVALID_MESSAGE,
    INVALID_AUTH,
    UNAUTHENTICATED_USER,

    // USER DISCONNECTS
    RESOURCE_UNAVAILABLE,
    CLOSED_CONVERSATION,

    // SERVER LIMIT
    EXCEEDED_CLIENT_MAX,

    // SERVER ERRORS
    PROGRAMMING_ERROR,
    INSUFFICIENT_BUFFER_SPACE,
    INSUFFICIENT_MEMORY,
    ERROR
};