#pragma once

enum class Status : uint8_t{
    // INFORMATIONAL
    SUCCESS = 1,
    NOTHING_TO_READ = 2,
    INCOMPLETE_MESSAGE = 3,
    NOTHING_TO_DO = 4,
    EXCEEDED_CLIENT_BUFFER_SIZE = 5,

    // CLIENT ERRORS OR MALICIOUS USER
    INVALID_PROTOCOL = 6,
    INVALID_CLIENT = 7,
    INVALID_MESSAGE = 8,
    INVALID_AUTH = 9,
    UNAUTHENTICATED_USER = 10,

    // USER DISCONNECTS
    RESOURCE_UNAVAILABLE = 11,
    CLOSED_CONVERSATION = 12,

    // SERVER LIMIT
    EXCEEDED_CLIENT_MAX = 13,

    // SERVER ERRORS
    PROGRAMMING_ERROR = 14,
    INSUFFICIENT_BUFFER_SPACE = 15,
    INSUFFICIENT_MEMORY = 16,
    ERROR = 17
};