enum class Status : uint8_t{
    // INFORMATIONAL
    SUCCESS,
    NOTHING_TO_READ,
    INCOMPLETE_MESSAGE,
    NOTHING_TO_DO,

    // ERRORS OR MALICIOUS USER
    INVALID_CLIENT,
    INVALID_MESSAGE,
    UNAUTHENTICATED_USER,
    EXCEEDED_CLIENT_BUFFER_SIZE,

    // USER DISCONNECTS
    RESOURCE_UNAVAILABLE,
    CLOSED_CONVERSATION,

    // SERVER ERRORS
    EXCEEDED_CLIENT_MAX,
    INSUFFICIENT_BUFFER_SPACE,
    ERROR
};